application: depoisdavirgula
version: 3
runtime: python
api_version: 1

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py  

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
      
- url: /style
  static_dir: static/style

- url: /js
  static_dir: static/js

- url: /.*
  script: main.py
